CREATE TABLE `e_discovery` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `dis_cof_id` bigint(20) DEFAULT NULL COMMENT '配置id',
  `state` int(1) DEFAULT NULL COMMENT '任务状态：0 停止 1运行中',
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '删除标识:0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `index_del_flag` (`del_flag`,`tenant`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发现任务表';

CREATE TABLE `e_discovery_config` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  `start_ip` varchar(255) DEFAULT NULL COMMENT '起始IP',
  `end_ip` varchar(255) DEFAULT NULL COMMENT '结束IP',
  `snmp_version` int(1) DEFAULT NULL COMMENT 'SNMP版本',
  `snmp_port` int(6) DEFAULT NULL COMMENT 'SNMP端口',
  `timeout` int(6) DEFAULT NULL COMMENT '超时（ms）',
  `reTryies` int(2) DEFAULT NULL COMMENT '重试次数',
  `read_community` varchar(255) DEFAULT NULL COMMENT '可读团体号',
  `snmp_user` varchar(255) DEFAULT NULL COMMENT 'SNMP用户',
  `security_level` int(1) DEFAULT NULL COMMENT '安全模式',
  `auth_algorithm` int(1) DEFAULT NULL COMMENT '认证算法：MD5或者SHA',
  `auth_password` varchar(255) DEFAULT NULL COMMENT '认证密码',
  `privacy_algorithm` int(1) DEFAULT NULL COMMENT '加密算法',
  `privacy_password` varchar(255) DEFAULT NULL COMMENT '加密密码',
  `link_protocol` varchar(12) DEFAULT NULL COMMENT '链路发现协议:lldp stp rstp aft port',
  `description` varchar(2000) DEFAULT NULL COMMENT '描述',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) DEFAULT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_del_flag` (`del_flag`,`tenant`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自动发现配置信息';

CREATE TABLE `e_discovery_dev` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `dis_id` bigint(20) DEFAULT NULL COMMENT '执行发现Id',
  `name` varchar(100) DEFAULT NULL COMMENT '名称',
  `description` varchar(1000) DEFAULT NULL COMMENT '描述',
  `ip` varchar(100) DEFAULT NULL COMMENT 'IP',
  `mac` varchar(4000) DEFAULT NULL COMMENT 'MAC',
  `type` varchar(20) DEFAULT NULL COMMENT '设备类型',
  `state` int(1) DEFAULT NULL COMMENT '设备状态',
  `model` varchar(100) DEFAULT NULL COMMENT '设备型号',
  `sys_object_id` varchar(100) DEFAULT NULL COMMENT '对象iD',
  `monitor_id` bigint(20) DEFAULT NULL COMMENT '监控id',
  `snmp_version` int(1) DEFAULT NULL COMMENT 'SNMP版本',
  `snmp_port` int(6) DEFAULT NULL COMMENT 'SNMP端口',
  `read_community` varchar(255) DEFAULT NULL COMMENT '可读团体号',
  `snmp_user` varchar(255) DEFAULT NULL COMMENT 'SNMP用户',
  `security_level` int(1) DEFAULT NULL COMMENT '认证级别',
  `equip_id` bigint(20) DEFAULT NULL COMMENT '关联设备ID',
  `equip_name` varchar(255) DEFAULT NULL COMMENT '设备名称',
  `auth_algorithm` int(1) DEFAULT NULL COMMENT '认证算法：MD5或者SHA',
  `auth_password` varchar(255) DEFAULT NULL COMMENT '认证密码',
  `privacy_algorithm` int(1) DEFAULT NULL COMMENT '加密算法',
  `privacy_password` varchar(255) DEFAULT NULL COMMENT '加密密码',
  `create_time` date DEFAULT NULL,
  `update_time` date DEFAULT NULL,
  `creator_id` bigint(20) DEFAULT NULL,
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  `creator_name` varchar(32) DEFAULT NULL,
  `del_flag` char(1) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_dis_id` (`del_flag`,`dis_id`) USING BTREE,
  KEY `index_type` (`type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发现设备表';

CREATE TABLE `e_discovery_dev_fdb` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `dis_dev_id` bigint(20) NOT NULL COMMENT '发现设备ID',
  `dev_ip` varchar(100) NOT NULL COMMENT '设备IP',
  `mac` varchar(100) DEFAULT NULL COMMENT 'MAC地址',
  `port` bigint(20) DEFAULT NULL COMMENT '转发端口',
  `status` int(11) NOT NULL COMMENT '转发状态',
  `create_time` date DEFAULT NULL COMMENT '创建时间',
  `update_time` date DEFAULT NULL COMMENT '更新时间',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建者id',
  `creator_name` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建者名称',
  `del_flag` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '删除标识：0-未删除，1-已删除',
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_dis_fdb_ip` (`dev_ip`),
  KEY `idx_dis_fdb_mac` (`mac`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='交换机的mac地址学习表';

CREATE TABLE `e_discovery_dev_port` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `dis_dev_id` bigint(20) NOT NULL COMMENT '发现设备ID',
  `name` varchar(100) DEFAULT NULL COMMENT '端口名称',
  `port_index` int(11) DEFAULT NULL COMMENT '索引',
  `mac` varchar(100) DEFAULT NULL COMMENT 'mac',
  `description` varchar(1000) DEFAULT NULL COMMENT '描述',
  `type` varchar(10) DEFAULT NULL COMMENT '端口类型',
  `admin_status` int(1) DEFAULT NULL COMMENT '管理状态1-连接，2-未连接',
  `oper_status` int(1) DEFAULT NULL COMMENT '操作状态1-开启，2-关闭',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建者id',
  `creator_name` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建者名称',
  `del_flag` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '删除标识：0-未删除，1-已删除',
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_del_flag` (`del_flag`) USING BTREE,
  KEY `index_dev_id` (`dis_dev_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='端口表';

CREATE TABLE `e_discovery_exec` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `dis_id` bigint(20) NOT NULL COMMENT '发现ID-e_discovery',
  `start_ip` varchar(255) DEFAULT NULL COMMENT '起始IP',
  `end_ip` varchar(255) DEFAULT NULL COMMENT '结束IP',
  `result_code` int(1) DEFAULT NULL COMMENT '执行结果编码',
  `result_msg` varchar(2000) DEFAULT NULL COMMENT '执行结果消息',
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) DEFAULT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  KEY `index_del_flag` (`del_flag`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自动发现执行记录表';

CREATE TABLE `e_discovery_exec_log` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `dis_id` bigint(20) NOT NULL COMMENT '发现ID-e_discovery',
  `exec_id` bigint(20) NOT NULL COMMENT '执行ID',
  `msg_type` int(1) DEFAULT NULL COMMENT '消息类型:0 正常 1警告 2错误',
  `msg` varchar(2000) DEFAULT NULL COMMENT '消息',
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) DEFAULT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  KEY `index_exec_id` (`exec_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自动发现执行记录明细表';

CREATE TABLE `e_discovery_link` (
  `id` bigint(20) NOT NULL COMMENT 'ID',
  `link_name` varchar(500) DEFAULT NULL COMMENT '链路名称',
  `link_code` varchar(500) DEFAULT NULL COMMENT '链路编码 ',
  `start_dev_id` bigint(20) NOT NULL COMMENT '起始设备id',
  `start_dev_name` varchar(100) DEFAULT NULL COMMENT '起始设备名称',
  `end_dev_id` bigint(20) NOT NULL COMMENT '终端设备ID',
  `end_dev_name` varchar(100) DEFAULT NULL COMMENT '终端设备名称',
  `start_port_id` bigint(20) DEFAULT NULL COMMENT '起始设备端口id',
  `start_port_name` varchar(100) DEFAULT NULL COMMENT '起始设备端口名称',
  `end_port_id` bigint(20) DEFAULT NULL COMMENT '终端设备端口id',
  `end_port_name` varchar(100) DEFAULT NULL COMMENT '终端设备端口名称',
  `create_time` date DEFAULT NULL COMMENT '创建时间',
  `update_time` date DEFAULT NULL COMMENT '更新时间',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建者id',
  `creator_name` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建者名称',
  `del_flag` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '删除标识：0-未删除，1-已删除',
  `tenant` bigint(20) DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_del_flag` (`del_flag`,`tenant`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

